debug

diff --git a/.github/workflows/build_deploy_test.yml b/.github/workflows/build_deploy_test.yml
--- a/.github/workflows/build_deploy_test.yml
+++ b/.github/workflows/build_deploy_test.yml
@@ -673,12 +673,18 @@ jobs:
         uses: nick-fields/retry@v3
         with:
           max_attempts: 15
-          retry_on: timeout
+          retry_on: error
           timeout_minutes: 3
           command: |
-            curl --connect-timeout 0 --max-time 0 -v -f -X POST https://${{ needs.runpod-deploy-orchestrator.outputs.instance_id }}-${{ env.ORCH_PORT }}.proxy.runpod.net/check-result \
-                  -H "Content-Type: application/json" \
-                  --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_ORCH_LLM }}
+            response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+                            --connect-timeout 0 --max-time 0 -v -f -X POST \
+                            https://${{ needs.runpod-deploy-orchestrator.outputs.instance_id }}-${{ env.ORCH_PORT }}.proxy.runpod.net/check-result \
+                            -H "Content-Type: application/json" \
+                            --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_ORCH_LLM }})
+            if [ "$response" -ne 200 ]; then
+              echo "Request failed with status code $response"
+              exit 1
+            fi
     outputs:
       instance_id: ${{ needs.runpod-deploy-orchestrator.outputs.instance_id }}
   
@@ -699,12 +705,18 @@ jobs:
         uses: nick-fields/retry@v3
         with:
           max_attempts: 10
-          retry_on: timeout
+          retry_on: error
           timeout_minutes: 3
           command: |
-            curl --connect-timeout 0 --max-time 0 -v -f -X POST https://${{ needs.runpod-test-orch-llm.outputs.instance_id }}-${{ env.ORCH_PORT }}.proxy.runpod.net/check-result \
-                  -H "Content-Type: application/json" \
-                  --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_ORCH_TXT2IMG }}
+            response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+                            --connect-timeout 0 --max-time 0 -v -f -X POST \
+                            https://${{ needs.runpod-test-orch-llm.outputs.instance_id }}-${{ env.ORCH_PORT }}.proxy.runpod.net/check-result \
+                            -H "Content-Type: application/json" \
+                            --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_ORCH_TXT2IMG }})
+            if [ "$response" -ne 200 ]; then
+              echo "Request failed with status code $response"
+              exit 1
+            fi
     outputs:
       instance_id: ${{ needs.runpod-test-orch-llm.outputs.instance_id }}
 
@@ -743,7 +755,7 @@ jobs:
         id: deploy-orch
         run: |
           sleep 5
-          response=$(curl --connect-timeout 0 --max-time 0 --retry 5 -X POST https://runpod-manager.onrender.com/create-instance \
+          response=$(curl --connect-timeout 5 --max-time 800 -X POST https://runpod-manager.onrender.com/create-instance \
                           -H "Content-Type: application/json" \
                           -H "API_KEY: ${{ secrets.RUNPOD_MANAGER_API_KEY }}" \
                           -d '{
@@ -761,6 +773,14 @@ jobs:
                             ],
                             "env_vars": {}
                           }')
+          http_code=$(echo "$response" | tail -n1)
+          response_body=$(echo "$response" | sed '$d')
+          
+          if [ "$http_code" -ge 400 ]; then
+            echo "Request failed with status code $http_code"
+            echo "Response: $response_body"
+            exit 1
+          fi
           instance_id=$(echo "$response" | jq -r '.id')
           echo "::set-output name=instance_id::$instance_id"
         timeout-minutes: 30
@@ -781,19 +801,32 @@ jobs:
       - name: Load model
         timeout-minutes: 20
         run: |
-          curl --connect-timeout 0 --max-time 0 -v -X POST https://${{ needs.runpod-deploy-llm-server.outputs.instance_id }}-${{ env.LLM_PORT }}.proxy.runpod.net/load_model \
-                  -H "Content-Type: application/json" \
-                  --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_LLM_LOAD }}
+          response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+                          --connect-timeout 0 --max-time 0 -v -X POST \
+                          https://${{ needs.runpod-deploy-llm-server.outputs.instance_id }}-${{ env.LLM_PORT }}.proxy.runpod.net/load_model \
+                          -H "Content-Type: application/json" \
+                          --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_LLM_LOAD }})
+          if [ "$response" -ne 200 ]; then
+            echo "Request failed with status code $response"
+            exit 1
+          fi
 
       - name: Test Runpod LLM
         uses: nick-fields/retry@v3
         with:
           max_attempts: 9
+          retry_on: error
           timeout_minutes: 5
           command: |
-            curl --connect-timeout 0 --max-time 0 -v -X POST https://${{ needs.runpod-deploy-llm-server.outputs.instance_id }}-${{ env.LLM_PORT }}.proxy.runpod.net/generate_text \
-                  -H "Content-Type: application/json" \
-                  --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_LLM_QUERY }}
+            response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+                            --connect-timeout 0 --max-time 0 -v -X POST \
+                            https://${{ needs.runpod-deploy-llm-server.outputs.instance_id }}-${{ env.LLM_PORT }}.proxy.runpod.net/generate_text \
+                            -H "Content-Type: application/json" \
+                            --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_LLM_QUERY }})
+            if [ "$response" -ne 200 ]; then
+              echo "Request failed with status code $response"
+              exit 1
+            fi
 
     outputs:
       instance_id: ${{ needs.runpod-deploy-llm-server.outputs.instance_id }}
@@ -833,7 +866,7 @@ jobs:
         id: deploy-orch
         run: |
           sleep 10
-          response=$(curl --connect-timeout 0 --max-time 0 --retry 5 -X POST https://runpod-manager.onrender.com/create-instance \
+          response=$(curl --connect-timeout 5 --max-time 800 -X POST https://runpod-manager.onrender.com/create-instance \
                           -H "Content-Type: application/json" \
                           -H "API_KEY: ${{ secrets.RUNPOD_MANAGER_API_KEY }}" \
                           -d '{
@@ -851,6 +884,14 @@ jobs:
                             ],
                             "env_vars": {}
                           }')
+          http_code=$(echo "$response" | tail -n1)
+          response_body=$(echo "$response" | sed '$d')
+          
+          if [ "$http_code" -ge 400 ]; then
+            echo "Request failed with status code $http_code"
+            echo "Response: $response_body"
+            exit 1
+          fi
           instance_id=$(echo "$response" | jq -r '.id')
           echo "::set-output name=instance_id::$instance_id"
         timeout-minutes: 30
@@ -872,12 +913,18 @@ jobs:
         uses: nick-fields/retry@v3
         with:
           max_attempts: 9
-          retry_on: timeout
+          retry_on: error
           timeout_minutes: 5
           command: |
-            curl --connect-timeout 0 --max-time 0 -v -X POST https://${{ needs.runpod-deploy-image-server.outputs.instance_id }}-${{ env.IMAGE_PORT }}.proxy.runpod.net/txt2img \
-                -H "Content-Type: application/json" \
-                --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_IMAGE_TXT2IMG }}
+            response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+                            --connect-timeout 0 --max-time 0 -v -X POST \
+                            https://${{ needs.runpod-deploy-image-server.outputs.instance_id }}-${{ env.IMAGE_PORT }}.proxy.runpod.net/txt2img \
+                            -H "Content-Type: application/json" \
+                            --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_IMAGE_TXT2IMG }})
+            if [ "$response" -ne 200 ]; then
+              echo "Request failed with status code $response"
+              exit 1
+            fi
     outputs:
       instance_id: ${{ needs.runpod-deploy-image-server.outputs.instance_id }}
   
@@ -898,12 +945,18 @@ jobs:
         uses: nick-fields/retry@v3
         with:
           max_attempts: 9
-          retry_on: timeout
+          retry_on: error
           timeout_minutes: 10
           command: |
-            curl --connect-timeout 0 --max-time 0 -v -X POST https://${{ needs.runpod-test-image.outputs.instance_id }}-${{ env.IMAGE_PORT }}.proxy.runpod.net/avatar \
-                -H "Content-Type: application/json" \
-                --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_IMAGE_AVATAR }}
+            response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+                            --connect-timeout 0 --max-time 0 -v -X POST \
+                            https://${{ needs.runpod-test-image.outputs.instance_id }}-${{ env.IMAGE_PORT }}.proxy.runpod.net/avatar \
+                            -H "Content-Type: application/json" \
+                            --data-binary @/home/runner/work/tau-workers/tau-workers/${{ env.TEST_JSON_FOLDER }}/${{ env.RUNPOD_TEST_IMAGE_AVATAR }})
+            if [ "$response" -ne 200 ]; then
+              echo "Request failed with status code $response"
+              exit 1
+            fi
     outputs:
       instance_id: ${{ needs.runpod-test-image.outputs.instance_id }}
 
